name: Sync README.md to GitHub Pages

on:
  push:
    branches:
      - main  # Задача запускается при каждом пуше в основную ветку
    paths:
      - README.md  # Только изменения в README.md будут запускать workflow
  workflow_dispatch:  # Вручную можно запускать сборку через GitHub интерфейс

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Create README.html from README.md
        run: |
          echo '<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><title>Документация</title></head><body>' > README.html
          pandoc README.md -f markdown -t html >> README.html
          echo '</body></html>' >> README.html

      - name: Проверка токена и доступности репозитория
        run: |
          echo "Токен доступен: ${{ secrets.GITHUB_TOKEN }}"
          git remote -v

      - name: Commit and push README.html to GitHub Pages repository
        run: |
          # Клонируем репозиторий GitHub Pages
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Nik497926/nik497926.github.io.git
          cp README.html nik497926.github.io/
          cd nik497926.github.io

          # Настроим Git
          git config --global user.name "GitHub Actions"
