name: Sync README to GitHub Pages

on:
  push:
    branches:
      - main  # Или другая основная ветка
    paths:
      - 'README.md'  # Треккинг изменений в README.md

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Create README.html from README.md
        run: |
          echo '<!DOCTYPE html><html lang="ru"><head><meta charset="UTF-8"><title>Документация</title></head><body>' > README.html
          pandoc README.md -f markdown -t html >> README.html
          echo '</body></html>' >> README.html

      - name: Checkout the target GitHub Pages repository
        uses: actions/checkout@v3
        with:
          repository: Nik497926/nik497926.github.io  # Репозиторий GitHub Pages
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token для доступа к репозиторию
          path: pages_repo  # Путь, в который клонируется репозиторий GitHub Pages

      - name: Copy README.html to GitHub Pages repository
        run: |
          cp README.html pages_repo/  # Копирование файла в папку GitHub Pages
          cd pages_repo
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.html
          git commit -m "Обновление README.html" || echo "Нет изменений"  # Избежим ошибки, если изменений нет
          git push
